### ISSUE TITLE
ERROR Socket Error 12

### ISSUE THREAD

**Issue by YimengZhu** [ELITR/pv-platform-sample-connector#3]
Hi,

I've tried to connect the mediator with ebclient. However I got socket error 12. Is there any way to fix it?

`
xxx@rg3hpc1:pv-platform-sample-connector/Linux$ ./ebclient -s i13srv53.ira.uka.de -p 4443 -f en-EU -i en-EU -t unseg-text -r ../audio/talk1313.mp4-16kHz.wav > hypo.stm
INFO trying to connect to i13srv53.ira.uka.de at port 4443.
ERROR Socket Error 12 
ERROR (src/MCloud.c,2137): mcloudConnect: Connecting to i13srv53.ira.uka.de:4443
ERROR while trying to connect.
`

Thanks in advance.

**Comment by Gldkslfmsd** [comment]
Hello,
please contact the maintainer of your mediator.
